pipeline {
    agent {
        docker {
        }
    }
    environment {
        DOCKER_HOST = "tcp://192.168.122.5:2375"
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create Tomcat Docker Image') {
            steps {
                sh 'pwd'
                sh 'ls -a'
                script {
                    def imageTag = "tomcatsamplewebapp:${env.BUILD_ID}"
                    sh "docker build -t ${imageTag} ./java-tomcat-sample-docker"
                }
            }
        }
    }
}
